### ISSUE TITLE
运行时显示/usr/local/tbb-2019_U8/lib/libtbb.so: file too short

### ISSUE THREAD

**Issue by cheserio** [NingMingHao/Yolov8TensorrtRos#2]
运行时显示/usr/local/tbb-2019_U8/lib/libtbb.so: file too short 但在这个路径下是有对应文件的

**Comment by NingMingHao** [comment]
This seems related to how you install the necessary library ttb for opencv, what I did is install libttb using apt, it looks you customized the installation of libttb.

So I suggest you first try to specify the include and lib dir like what happens to openblas:

-D OpenBLAS_INCLUDE_DIR=/usr/include/openblas \
-D OpenBLAS_LIB=/usr/lib/x86_64-linux-gnu/libopenblas.so \
