### ISSUE TITLE
Could NOT find TensorRT (missing: TensorRT_INCLUDE_DIR)

### ISSUE THREAD

**Issue by Pradur241** [NingMingHao/Yolov8TensorrtRos#9]
I tried to install this package on my laptop. tensorrt cannot be installed as written in your manual, so I installed tensorrt as tar. But an error is reported when catkin_make.
![2024-03-31_14-05](https://github.com/NingMingHao/Yolov8TensorrtRos/assets/57956342/cf0f7b9d-f104-432d-b7c1-e9078f0f51e5)

**Comment by NingMingHao** [comment]
Hi, please check if you have installed and setup the tensorrt properly. Please follow this link https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar and make sure you export the include dir in the bashrc.

**Comment by Pradur241** [comment]
Thanks for the reply! I've solved it by adding TensorRT's path into FindTensorrt.cmake
